apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app-deployment
  labels:
     app: spring-boot-app
     type: back-end
spec:
  template:
     metadata:
       name: spring-boot-app-pod
       labels: 
         app: spring-boot
         type: back-end
     spec:
         containers:
           - name: spring-boot-app-cont
             image: "dberenguerdevcenter/spring-boot-app:latest"
             imagePullPolicy: Always
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot
      type: back-end
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
spec:
  selector:
    app: spring-boot
  type: NodePort  
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 80
      nodePort: 30000